-- Eğer tablo zaten varsa sil (sadece gelişim ortamında güvenli)
DROP TABLE IF EXISTS products;

-- Tabloyu oluştur (Product.java'daki alanlara uygun olmalı)
CREATE TABLE products (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          price DOUBLE NOT NULL,
                          quantity BIGINT DEFAULT 0,
                          category VARCHAR(100)
);

INSERT INTO products (name, price, quantity, category) VALUES
                                                           ('Samsung Galaxy S24 Ultra', 1299.99, 150, 'Electronics'),
                                                           ('Apple iPhone 16 Pro Max', 1499.99, 120, 'Electronics'),
                                                           ('Sony WH-1000XM5 Headphones', 349.00, 200, 'Electronics'),
                                                           ('LG OLED TV C3 65 inch', 1899.00, 75, 'Electronics'),
                                                           ('Dell XPS 15 Laptop', 1799.00, 90, 'Electronics'),
                                                           ('HP Spectre x360 Laptop', 1399.00, 80, 'Electronics'),
                                                           ('Bose QuietComfort Earbuds II', 279.00, 180, 'Electronics'),
                                                           ('Apple iPad Air 6', 799.00, 110, 'Electronics'),
                                                           ('Microsoft Surface Pro 10', 999.00, 60, 'Electronics'),
                                                           ('Google Pixel 8 Pro', 899.00, 100, 'Electronics'),
                                                           ('Nintendo Switch OLED', 349.99, 130, 'Electronics'),
                                                           ('PlayStation 5 Slim', 499.99, 95, 'Electronics'),
                                                           ('Xbox Series X', 499.99, 85, 'Electronics'),
                                                           ('Dyson Corrale Hair Straightener', 499.00, 50, 'Electronics'),
                                                           ('Philips Hue Smart Bulb Kit', 89.99, 300, 'Electronics'),
                                                           ('Ring Video Doorbell 4', 199.99, 100, 'Electronics'),
                                                           ('Arlo Pro 4 Security Camera', 179.99, 70, 'Electronics'),
                                                           ('Garmin Fenix 7 Smartwatch', 699.00, 40, 'Electronics'),
                                                           ('DJI Mini 4 Pro Drone', 959.00, 30, 'Electronics'),
                                                           ('GoPro HERO12 Black', 399.99, 60, 'Electronics'),
                                                           ('Amazon Echo Show 10', 249.99, 110, 'Electronics'),
                                                           ('Google Nest Hub Max', 229.00, 90, 'Electronics'),
                                                           ('TP-Link Archer AXE75 Wi-Fi 6E Router', 199.99, 120, 'Electronics'),
                                                           ('Samsung Galaxy Tab S9', 799.00, 80, 'Electronics'),
                                                           ('Roku Ultra Streaming Player', 99.99, 150, 'Electronics'),
                                                           ('Fire TV Stick 4K Max', 59.99, 250, 'Electronics'),
                                                           ('Anker PowerCore III Elite', 99.99, 180, 'Electronics'),
                                                           ('Logitech MX Master 3S Mouse', 99.99, 220, 'Electronics'),
                                                           ('Logitech MX Mechanical Keyboard', 169.99, 190, 'Electronics'),
                                                           ('Western Digital 4TB External HDD', 119.99, 160, 'Electronics'),
                                                           ('Men''s Classic T-Shirt', 25.00, 500, 'Apparel'),
                                                           ('Women''s High-Waisted Jeans', 59.99, 450, 'Apparel'),
                                                           ('Unisex Hoodie', 45.00, 380, 'Apparel'),
                                                           ('Running Shoes - Men', 89.99, 320, 'Apparel'),
                                                           ('Running Shoes - Women', 89.99, 300, 'Apparel'),
                                                           ('Summer Dress', 35.00, 400, 'Apparel'),
                                                           ('Winter Coat - Men', 120.00, 200, 'Apparel'),
                                                           ('Winter Coat - Women', 120.00, 180, 'Apparel'),
                                                           ('Casual Sneakers', 65.00, 250, 'Apparel'),
                                                           ('Formal Shirt', 50.00, 280, 'Apparel'),
                                                           ('Yoga Pants', 30.00, 350, 'Apparel'),
                                                           ('Sport Socks 3-pack', 15.00, 600, 'Apparel'),
                                                           ('Leather Belt', 40.00, 200, 'Apparel'),
                                                           ('Denim Jacket', 70.00, 150, 'Apparel'),
                                                           ('Polo Shirt', 35.00, 300, 'Apparel'),
                                                           ('Swimming Trunks', 28.00, 220, 'Apparel'),
                                                           ('Bikini Set', 38.00, 250, 'Apparel'),
                                                           ('Kids T-Shirt', 15.00, 400, 'Apparel'),
                                                           ('Baby Onesie', 20.00, 350, 'Apparel'),
                                                           ('Work Boots', 95.00, 100, 'Apparel'),
                                                           ('Robot Vacuum Cleaner', 299.00, 100, 'Home & Living'),
                                                           ('Smart Coffee Maker', 120.00, 150, 'Home & Living'),
                                                           ('Air Fryer 5.8 QT', 89.99, 180, 'Home & Living'),
                                                           ('Blender High Power', 75.00, 160, 'Home & Living'),
                                                           ('Queen Size Bed Frame', 350.00, 50, 'Home & Living'),
                                                           ('Memory Foam Pillow', 40.00, 300, 'Home & Living'),
                                                           ('Weighted Blanket', 60.00, 220, 'Home & Living'),
                                                           ('Aromatherapy Diffuser', 25.00, 400, 'Home & Living'),
                                                           ('Cast Iron Skillet Set', 80.00, 120, 'Home & Living'),
                                                           ('Non-stick Cookware Set', 150.00, 90, 'Home & Living'),
                                                           ('Kitchen Mixer Stand', 250.00, 70, 'Home & Living'),
                                                           ('Handheld Vacuum', 55.00, 200, 'Home & Living'),
                                                           ('Electric Kettle', 45.00, 250, 'Home & Living'),
                                                           ('Toaster Oven', 65.00, 180, 'Home & Living'),
                                                           ('Set of Bath Towels', 30.00, 300, 'Home & Living'),
                                                           ('Shower Head Filter', 20.00, 400, 'Home & Living'),
                                                           ('Smart Lock', 150.00, 80, 'Home & Living'),
                                                           ('Indoor Plant - Fiddle Leaf Fig', 60.00, 50, 'Home & Living'),
                                                           ('Outdoor Patio Set', 400.00, 20, 'Home & Living'),
                                                           ('Gardening Tool Set', 45.00, 100, 'Home & Living'),
                                                           ('The Midnight Library', 15.99, 500, 'Books'),
                                                           ('Atomic Habits', 12.50, 600, 'Books'),
                                                           ('Project Hail Mary', 14.00, 450, 'Books'),
                                                           ('Where the Crawdads Sing', 13.75, 550, 'Books'),
                                                           ('Educated: A Memoir', 11.99, 480, 'Books'),
                                                           ('Dune (Paperback)', 10.50, 300, 'Books'),
                                                           ('The Great Gatsby', 8.99, 700, 'Books'),
                                                           ('1984 (Centennial Edition)', 9.50, 650, 'Books'),
                                                           ('The Lord of the Rings Box Set', 45.00, 150, 'Books'),
                                                           ('Harry Potter and the Sorcerer''s Stone', 10.99, 400, 'Books'),
                                                           ('LEGO Star Wars Millennium Falcon', 169.99, 70, 'Toys & Hobbies'),
                                                           ('Remote Control Car 4x4', 55.00, 150, 'Toys & Hobbies'),
                                                           ('Board Game - Catan', 49.99, 120, 'Toys & Hobbies'),
                                                           ('Art Easel for Kids', 35.00, 200, 'Toys & Hobbies'),
                                                           ('Puzzle 1000 Pieces - Ocean View', 18.00, 250, 'Toys & Hobbies'),
                                                           ('Model Airplane Kit', 70.00, 80, 'Toys & Hobbies'),
                                                           ('Digital Camera for Kids', 45.00, 100, 'Toys & Hobbies'),
                                                           ('Science Experiment Kit', 30.00, 180, 'Toys & Hobbies'),
                                                           ('Drone for Beginners', 85.00, 90, 'Toys & Hobbies'),
                                                           ('Action Figure Collectible', 25.00, 300, 'Toys & Hobbies'),
                                                           ('Yoga Mat Anti-slip', 25.00, 300, 'Sports & Outdoors'),
                                                           ('Camping Tent 2-Person', 89.99, 100, 'Sports & Outdoors'),
                                                           ('Hiking Backpack 60L', 75.00, 120, 'Sports & Outdoors'),
                                                           ('Water Bottle Insulated', 18.00, 400, 'Sports & Outdoors'),
                                                           ('Dumbbell Set 20lb', 40.00, 150, 'Sports & Outdoors'),
                                                           ('Resistance Bands Set', 20.00, 350, 'Sports & Outdoors'),
                                                           ('Bicycle Helmet Adult', 45.00, 180, 'Sports & Outdoors'),
                                                           ('Portable Camping Chair', 30.00, 250, 'Sports & Outdoors'),
                                                           ('Fishing Rod and Reel Combo', 60.00, 90, 'Sports & Outdoors'),
                                                           ('Fitness Tracker Watch', 70.00, 200, 'Sports & Outdoors'),
                                                           ('Facial Cleansing Brush', 35.00, 200, 'Beauty & Personal Care'),
                                                           ('Electric Toothbrush', 55.00, 180, 'Beauty & Personal Care'),
                                                           ('Hair Dryer Professional', 70.00, 150, 'Beauty & Personal Care'),
                                                           ('Moisturizing Face Cream', 28.00, 300, 'Beauty & Personal Care'),
                                                           ('Shampoo & Conditioner Set', 22.00, 400, 'Beauty & Personal Care'),
                                                           ('Perfume for Women (50ml)', 80.00, 100, 'Beauty & Personal Care'),
                                                           ('Cologne for Men (100ml)', 70.00, 90, 'Beauty & Personal Care'),
                                                           ('Sunscreen SPF 50', 18.00, 250, 'Beauty & Personal Care'),
                                                           ('Body Lotion Hydrating', 15.00, 350, 'Beauty & Personal Care'),
                                                           ('Manicure Pedicure Kit', 25.00, 120, 'Beauty & Personal Care'),
                                                           ('Stand Mixer', 200.00, 80, 'Kitchen Appliances'),
                                                           ('Slow Cooker 6 Quart', 45.00, 150, 'Kitchen Appliances'),
                                                           ('Food Processor 12-Cup', 90.00, 100, 'Kitchen Appliances'),
                                                           ('Espresso Machine', 350.00, 60, 'Kitchen Appliances'),
                                                           ('Microwave Oven Compact', 70.00, 120, 'Kitchen Appliances'),
                                                           ('Dish Drying Rack', 25.00, 250, 'Kitchen Appliances'),
                                                           ('Electric Griddle', 50.00, 180, 'Kitchen Appliances'),
                                                           ('Hand Mixer', 30.00, 200, 'Kitchen Appliances'),
                                                           ('Waffle Maker', 40.00, 160, 'Kitchen Appliances'),
                                                           ('Electric Can Opener', 20.00, 220, 'Kitchen Appliances'),
                                                           ('Baby Stroller', 180.00, 40, 'Baby Products'),
                                                           ('Diaper Bag Backpack', 60.00, 100, 'Baby Products'),
                                                           ('Baby Monitor with Camera', 95.00, 70, 'Baby Products'),
                                                           ('Baby Carrier Ergonomic', 70.00, 80, 'Baby Products'),
                                                           ('Baby Bottle Set', 30.00, 200, 'Baby Products'),
                                                           ('Baby Bouncer Seat', 50.00, 120, 'Baby Products'),
                                                           ('Baby Play Mat', 40.00, 150, 'Baby Products'),
                                                           ('Infant Bathtub', 25.00, 180, 'Baby Products'),
                                                           ('Baby Food Maker', 80.00, 60, 'Baby Products'),
                                                           ('Nursery Organizer', 35.00, 110, 'Baby Products'),
                                                           ('Dog Food Premium 30lb', 55.00, 100, 'Pet Supplies'),
                                                           ('Cat Litter Scoop', 10.00, 300, 'Pet Supplies'),
                                                           ('Pet Bed Large', 40.00, 80, 'Pet Supplies'),
                                                           ('Cat Tree Condo', 80.00, 50, 'Pet Supplies'),
                                                           ('Dog Leash Ret retractable', 20.00, 250, 'Pet Supplies'),
                                                           ('Bird Cage Medium', 60.00, 30, 'Pet Supplies'),
                                                           ('Fish Tank 10 Gallon', 45.00, 70, 'Pet Supplies'),
                                                           ('Hamster Cage', 35.00, 90, 'Pet Supplies'),
                                                           ('Pet Grooming Kit', 28.00, 150, 'Pet Supplies'),
                                                           ('Dog Toys Variety Pack', 15.00, 200, 'Pet Supplies'),
                                                           ('Ergonomic Office Chair', 220.00, 60, 'Office Supplies'),
                                                           ('Wireless Keyboard and Mouse Combo', 50.00, 180, 'Office Supplies'),
                                                           ('Printer All-in-One', 150.00, 70, 'Office Supplies'),
                                                           ('Shredder Paper', 80.00, 90, 'Office Supplies'),
                                                           ('Desk Lamp LED', 30.00, 250, 'Office Supplies'),
                                                           ('File Cabinet 3-Drawer', 100.00, 40, 'Office Supplies'),
                                                           ('Laptop Stand Adjustable', 40.00, 160, 'Office Supplies'),
                                                           ('Whiteboard Magnetic', 60.00, 80, 'Office Supplies'),
                                                           ('Set of Gel Pens', 12.00, 300, 'Office Supplies'),
                                                           ('Notebook College Ruled 6-pack', 18.00, 400, 'Office Supplies'),
                                                           ('Bluetooth Speaker Mini', 30.00, 250, 'Electronics'),
                                                           ('USB-C Hub Multiport', 40.00, 180, 'Electronics'),
                                                           ('Wireless Charger Stand', 25.00, 300, 'Electronics'),
                                                           ('Smart Plug 4-pack', 35.00, 220, 'Electronics'),
                                                           ('Fitness Smartwatch Basic', 50.00, 190, 'Electronics'),
                                                           ('External SSD 1TB', 110.00, 140, 'Electronics'),
                                                           ('Gaming Headset RGB', 65.00, 160, 'Electronics'),
                                                           ('Webcam 1080p HD', 45.00, 210, 'Electronics'),
                                                           ('Portable Projector Mini', 180.00, 70, 'Electronics'),
                                                           ('Smart Thermostat', 130.00, 90, 'Electronics'),
                                                           ('Security Camera Indoor', 70.00, 130, 'Electronics'),
                                                           ('VR Headset Entry-Level', 250.00, 40, 'Electronics'),
                                                           ('Digital Photo Frame', 60.00, 110, 'Electronics'),
                                                           ('Smart Scale Bluetooth', 40.00, 170, 'Electronics'),
                                                           ('E-Reader Kindle Paperwhite', 139.00, 120, 'Electronics'),
                                                           ('Men''s Dress Shirt Slim Fit', 65.00, 200, 'Apparel'),
                                                           ('Women''s Cardigan Knit', 40.00, 250, 'Apparel'),
                                                           ('Kids Winter Jacket', 75.00, 150, 'Apparel'),
                                                           ('Baby Sleepsuit Organic', 30.00, 300, 'Apparel'),
                                                           ('Sport Shorts', 20.00, 400, 'Apparel'),
                                                           ('Casual Dress', 45.00, 300, 'Apparel'),
                                                           ('Winter Scarf', 18.00, 350, 'Apparel'),
                                                           ('Touchscreen Gloves', 15.00, 400, 'Apparel'),
                                                           ('Swim Goggles', 12.00, 280, 'Apparel'),
                                                           ('Rain Jacket Lightweight', 80.00, 120, 'Apparel'),
                                                           ('Stand Mixer Pro', 300.00, 50, 'Kitchen Appliances'),
                                                           ('Juicer Cold Press', 150.00, 70, 'Kitchen Appliances'),
                                                           ('Electric Pressure Cooker', 95.00, 110, 'Kitchen Appliances'),
                                                           ('Water Filter Pitcher', 30.00, 250, 'Kitchen Appliances'),
                                                           ('Digital Kitchen Scale', 20.00, 300, 'Kitchen Appliances'),
                                                           ('Reusable Food Storage Containers (Set)', 35.00, 280, 'Kitchen Appliances'),
                                                           ('Silicone Baking Mat Set', 18.00, 350, 'Kitchen Appliances'),
                                                           ('Vegetable Chopper Manual', 22.00, 200, 'Kitchen Appliances'),
                                                           ('Ice Cream Maker Home', 60.00, 90, 'Kitchen Appliances'),
                                                           ('Coffee Grinder Electric', 40.00, 180, 'Kitchen Appliances');